### ISSUE TITLE
\number seems not correctly supported

### ISSUE THREAD

**Issue by Skillmon** [blefloch/latex-unravel#37]
If the argument to `\unravel` is just a valid `\number` expression an error is thrown:

```
\documentclass{article}
\usepackage{unravel}
\begin{document}
\unravel{\number`a}
\end{document}
```

This throws:

```
Runaway argument?
\__unravel_print_outcome: \__unravel_final_test: \__unravel_exit_point: \ETC.
! File ended while scanning use of \__unravel_exit_error:w.
<inserted text>
                \par
```

**Comment by jfbu** [comment]
The expression is not properly terminated: with ``\unravel{\number`a }``  (added space token at the end) there is no issue.

**Comment by jfbu** [comment]
Same thing for `\unravel{\the\count0}` versus `\unravel{\the\count0 }`.

**Comment by blefloch** [comment]
I've opted for producing an error and adding \relax.  It's not
fool-proof, e.g. \unravel{\unexpanded} will repeatedly add \relax, but
since it produces an error, that's more or less ok I guess.
