### ISSUE TITLE
Dimen assignment with factor in front of an implicit `<number>` fails

### ISSUE THREAD

**Issue by jfbu** [blefloch/latex-unravel#39]
Sorry for bad vocabulary (not time to check e.g. TeX by Topic for exact one).

This fails with current master at 9461aa1fdf4

```latex
\documentclass{article}
\usepackage{unravel}

\begin{document}

% raises error
\unravel{\dimen255=3\catcode`\p\relax}


% this is ok
\dimen255=3\catcode`\p\relax

\number\dimen255 % 33 = 3 times 11

\end{document}
```

I have inserted the `\relax` only for extra safety.

**Comment by blefloch** [comment]
Thanks for the report.  It's always appreciated.
