### ISSUE TITLE
Macro in that grabs \fi causes 'the-last-unravel-finished-badly'

### ISSUE THREAD

**Issue by PhelypeOleinik** [blefloch/latex-unravel#44]
When a macro delimited by `\fi` is used in a conditional, `\unravel` seems to partially lose track of `\if`...`\fi` nesting and throws an error at the end:
```latex
\RequirePackage{unravel}
\def\aux\fi{}
\unravel{\ifx!!\aux\fi}
\stop
```
But the code execution seems to be carried out correctly.

---

Terminal output:
```none
======== Welcome to the unravel package ========
    "<|" denotes the output to TeX's stomach.
    "||" denotes tokens waiting to be used.
    "|>" denotes tokens that we will act on.
    Press <enter> to continue; 'h' <enter> for help.

|| 
|> \ifx !!\aux \fi 

[===== Step 1 =====] \ifx = \ifx
|| \ifx 
|> !!\aux \fi 

[===== Step 2 =====] Compare: \ifx !!=true
|| 
|> \aux \fi 

[===== Step 3 =====] \aux = macro:\fi ->
|| 
|> 

[===== End =====]

! Package unravel Error: Internal error: 'the-last-unravel-finished-badly'. 
(unravel)                Please report.

Type <return> to continue.
 ...                                              
                                                  
l.5 \unravel{\ifx!!\aux\fi}
                           
?
```

**Comment by blefloch** [comment]
On 4/29/21 3:59 AM, Phelype Oleinik wrote:
> When a macro delimited by |\fi| is used in a conditional, |\unravel| seems to
> partially lose track of |\if|...|\fi| nesting and throws an error at the end:

Hum, the problem is not \aux\fi, but the unfinished conditional: \unravel{\ifx
aa} gives the same error.  I'll take a look.

**Comment by PhelypeOleinik** [comment]
Duh, right, because I forgot the `\fi` in the definition of `\aux` _/facepalm_
