### ISSUE TITLE
`\scantokens` leaves extra pair of braces

### ISSUE THREAD

**Issue by muzimuzhi** [blefloch/latex-unravel#55]
For definition `\edef\x{\scantokens{abc\noexpand}`, if wrapped in `\unravel`, an extra pair of braces is added to the result of `\scantokens`.

```tex
\documentclass{article}
\usepackage{unravel}

\begin{document}
         \edef\x{\scantokens{abc\noexpand}}
\unravel{\edef\y{\scantokens{abc\noexpand}}}

\show\x % macro:->abc
\show\y % macro:->{abc} % WRONG DEFINITION

% another example without \edef
$a          \scantokens{+\noexpand}  b$
$a \unravel{\scantokens{+\noexpand}} b$ % output looks like $a{+}b$
\end{document}
```

**Comment by PhelypeOleinik** [comment]
Actually just `\unravel{\scantokens{+}}` adds the extra braces, and `\unravel{\edef\y{\scantokens{abc}}}` incorrectly works.

Bruno fixed `\scantokens` at the macro level ;-)
